# Generated by Django 5.0.6 on 2024-06-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateField()),
                ('CCS811_eCO2_ppm', models.IntegerField()),
                ('CCS811_Tvoc_ppm', models.IntegerField()),
                ('SCD41_CO2_ppm', models.IntegerField()),
                ('SCD41_Temp_mC', models.IntegerField()),
                ('SCD41_Humidity_mRH', models.IntegerField()),
                ('SPS30_Pm2_5', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
